title: GitBlog
description: Study notes and lecture reflections
url: "https://HyeonWooNa0861.github.io"
timezone: Asia/Seoul
future: true
markdown: kramdown
permalink: /:year/:month/:day/:title/
include:
  - _pics

collections:
  assignment:
    output: true
    permalink: /assignment/:path/
  research:
    output: true
    permalink: /research/:path/
  study:
    output: true
    permalink: /study/:path/
